services:
  web_app:
    build:
      context: .
    container_name: fastapi_app
    command: uvicorn main:app --host 0.0.0.0 --reload
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:123456@db:5432/mydatabase
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app

  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
